//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarInGarages = new HashSet<CarInGarage>();
            this.Events = new HashSet<Event>();
            this.Reminders = new HashSet<Reminder>();
        }
    
        public int CarID { get; set; }
        public int CarModelID { get; set; }
        public int Year { get; set; }
        public Nullable<int> ColorID { get; set; }
        public int FuelTypeID { get; set; }
        public Nullable<int> CarcaseTypeID { get; set; }
        public Nullable<int> GearBoxID { get; set; }
        public Nullable<int> EngineVolume { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> MonthMileage { get; set; }
        public string Comment { get; set; }
        public byte[] CarPhoto { get; set; }
        public bool CarVisible { get; set; }
        public bool CarIsReadOnly { get; set; }
        public string ImageType { get; set; }
    
        public virtual CarcaseType CarcaseType { get; set; }
        public virtual ICollection<CarInGarage> CarInGarages { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual Color Color { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual GearBoxType GearBoxType { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
    }
}
