//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int CarModelID { get; set; }
        public string CarModelName { get; set; }
        public int CarMarkID { get; set; }
        public bool IsUserModel { get; set; }
    
        public virtual CarMark CarMark { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
    }
}
