//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMark
    {
        public CarMark()
        {
            this.CarModels = new HashSet<CarModel>();
        }
    
        public int CarMarkID { get; set; }
        public string CarMarkName { get; set; }
        public bool IsUserMark { get; set; }
    
        public virtual ICollection<CarModel> CarModels { get; set; }
    }
}
