//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMark
    {
        public CarMark()
        {
            this.CarModels = new HashSet<CarModel>();
        }
    
        public int CarMarkID { get; set; }
        public string CarMarkName { get; set; }
        public bool IsUserMark { get; set; }
    
        public virtual ICollection<CarModel> CarModels { get; set; }
    }
}
