//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int CarModelID { get; set; }
        public string CarModelName { get; set; }
        public int CarMarkID { get; set; }
        public bool IsUserModel { get; set; }
    
        public virtual CarMark CarMark { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
    }
}
