//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Cars = new HashSet<Car>();
            this.Events = new HashSet<Event>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public string CultureName { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
