//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int EventTypeID { get; set; }
        public string EventTypeName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual User User { get; set; }
    }
}
