//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int EventTypeID { get; set; }
        public string EventTypeName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual User User { get; set; }
    }
}
