//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filling
    {
        public int FillingID { get; set; }
        public int FuelTypeID { get; set; }
        public Nullable<float> FuelCount { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public bool IsFullTank { get; set; }
        public bool IsForgotPreviousFilling { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual FuelType FuelType { get; set; }
    }
}
