//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelType
    {
        public FuelType()
        {
            this.Cars = new HashSet<Car>();
            this.Fillings = new HashSet<Filling>();
        }
    
        public int FuelTypeID { get; set; }
        public string FuelTypeName { get; set; }
        public string FuelMeasure { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Filling> Fillings { get; set; }
    }
}
