//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelType
    {
        public FuelType()
        {
            this.Cars = new HashSet<Car>();
            this.Fillings = new HashSet<Filling>();
        }
    
        public int FuelTypeID { get; set; }
        public string FuelTypeName { get; set; }
        public string FuelMeasure { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Filling> Fillings { get; set; }
    }
}
