//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GearBoxType
    {
        public GearBoxType()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int GearBoxID { get; set; }
        public string GearBoxName { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
    }
}
