//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string Theme { get; set; }
        public int ChainID { get; set; }
        public int SenderID { get; set; }
        public bool IsDeleteBySender { get; set; }
        public int RecipientID { get; set; }
        public bool IsDeleteByRecipient { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
