//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string Theme { get; set; }
        public int ChainID { get; set; }
        public int SenderID { get; set; }
        public bool IsDeleteBySender { get; set; }
        public int RecipientID { get; set; }
        public bool IsDeleteByRecipient { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
