//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int PlaceID { get; set; }
        public string PlaceName { get; set; }
        public bool IsFillingStation { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual User User { get; set; }
    }
}
