//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderID { get; set; }
        public int UserID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime FinishDateTime { get; set; }
        public string ReminderName { get; set; }
        public bool IsRemindByEmail { get; set; }
        public Nullable<int> ReminderCountOfMileage { get; set; }
        public Nullable<int> ReminderCountOfDays { get; set; }
        public bool IsReminderDone { get; set; }
        public int CarID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
