//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartType
    {
        public SparePartType()
        {
            this.Repairs = new HashSet<Repair>();
        }
    
        public int SparePartTypeID { get; set; }
        public string SparePartTypeName { get; set; }
    
        public virtual ICollection<Repair> Repairs { get; set; }
    }
}
