//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartType
    {
        public SparePartType()
        {
            this.Repairs = new HashSet<Repair>();
        }
    
        public int SparePartTypeID { get; set; }
        public string SparePartTypeName { get; set; }
    
        public virtual ICollection<Repair> Repairs { get; set; }
    }
}
