//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGarage.Logic.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VirtualGarageEntities : DbContext
    {
        public VirtualGarageEntities()
            : base("name=VirtualGarageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarcaseType> CarcaseTypes { get; set; }
        public DbSet<CarInGarage> CarInGarages { get; set; }
        public DbSet<CarMark> CarMarks { get; set; }
        public DbSet<CarModel> CarModels { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Filling> Fillings { get; set; }
        public DbSet<FuelType> FuelTypes { get; set; }
        public DbSet<GearBoxType> GearBoxTypes { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<Reminder> Reminders { get; set; }
        public DbSet<Repair> Repairs { get; set; }
        public DbSet<SparePartType> SparePartTypes { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
